# Generated by Django 5.0.4 on 2024-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='059999999', max_length=20),
            preserve_default=False,
        ),
    ]
